### ISSUE TITLE
Není zřejmé, jak se program chová při nalezení chybného řádku

### ISSUE THREAD

**Issue by xtompok** [nekola03/du2#8]
Vlivem výjimky se některé části kódu neprovedou, některé provedou a není úplně jasné, jakým způsobem se to projeví na výsledku. Bylo by vhodné to minimálně popsat do dokumentace, nebo lépe udělat kód jednoznačnější - řádek se úplně vynechá, program skončí a vypíše chybu, ...

**Comment by nekola03** [comment]
Propsal jsem do dokumentace, a doufám, že je to správně.
