### ISSUE TITLE
Zvláštní zacházení s `avYear`

### ISSUE THREAD

**Issue by xtompok** [nekola03/du2#9]
`avYear` je float, pak se nakrátko stane stringem, poté je z ní opět float a než se naděje, už je vynulována. Přišlo by mi vhodnější rovnou to formátování přiřazovat do `firstDayYear[5]`, čímž by se kód zkrátil a bylo by to čitelnější. Obdobně pro `avSevenDay`.

**Comment by nekola03** [comment]
Prosímtě podíváš se na to znovu, zda je to správně. Nejspíš jsem to pochopil, ale pro jistotu.
